version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_APP_NAME=HR Management System
      - NEXT_PUBLIC_COMPANY_NAME=Your Company
      - NEXT_PUBLIC_SUPPORT_EMAIL=support@example.com
      - NEXT_PUBLIC_ENABLE_NOTIFICATIONS=false
      - NEXT_PUBLIC_ENABLE_OFFLINE_MODE=true
      - NEXT_PUBLIC_ENABLE_ANALYTICS=false
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hr_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 